%a
x=audioread('C:\Users\LAPTOP\Downloads\guit2.wav');
frame=256;
ovrlp=0.5;
X=frame_wind(x,frame,ovrlp);
E=enframe(X);
ZCR=zecrora(X);
%b
a=0.4;
b=0.4;
voice=akfwnes(E,ZCR,a,b);
%c
Y1=vframes(X,voice);
y1=frame_recon(Y1,ovrlp);
Y2=uframes(X,voice);
y2=frame_recon(Y2,ovrlp);
soundsc(y1,16000);
soundsc(y2,16000);
plot(y1);
plot(y2);
soundsc(y1+y2,16000);
plot(y1+y2);
%d
x=audioread('C:\Users\LAPTOP\Documents\MATLAB\recording.wav');
X=frame_wind(x,frame,ovrlp);
y=frame_recon(X,ovrlp);
clear y
E=enframe(X);
ZCR=zecrora(X);
voice=akfwnes(E,ZCR,a,b);
Y1=vframes(X,voice);
y1=frame_recon(Y1,ovrlp);
Y2=uframes(X,voice);
y2=frame_recon(Y2,ovrlp);
soundsc(y1,16000);
soundsc(y2,16000);
plot(y1);
plot(y2);
soundsc(y1+y2,16000);
plot(y1+y2);
